apiVersion: v1
kind: Pod
metadata:
  name: "myFirstPod"
  namespace: default
  labels:
    app: "myFirstPod"
spec:
  containers:
  - name: myFirstPod
    image: "nginx:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always