---
- name: Scala il numero di repliche in Kubernetes
  hosts: localhost
  tasks:
    - name: Applicare la configurazione di scaling
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default('devops-pipeline-kubernetes/cluster/.kube/config') }}"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: clusterdeplo
            namespace: default
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: clusterdeplo
            template:
              metadata:
                labels:
                  app: clusterdeplo
              spec:
                containers:
                - name: clusterdeplo
                  image: giacomoalfani/asdn_project:latest
                  ports:
                  - containerPort: 80
