---
- name: Configura il Load Balancer in Kubernetes
  hosts: localhost
  tasks:
    - name: Applicare la configurazione del Load Balancer
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default('devops-pipeline-kubernetes/cluster/.kube/config') }}"
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: clusterdeplo-loadbalancer
            namespace: default
          spec:
            type: LoadBalancer
            selector:
              app: clusterdeplo
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
