apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mywebdeplo
  namespace: default
  labels:
    app:  mywebdeplo
spec:
  selector:
    matchLabels:
      app: mywebdeplo
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mywebdeplo
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  mywebdeplo
        image:  giacomoalfani/mywebserver:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
        ports:
        - containerPort:  80
          name:  mywebdeplo
      restartPolicy: Always